import { Metadata } from 'next';
import { Navbar } from '../../components/navbar';
import { Footer } from '../../components/footer';
import { Section } from '../../components/section';

export const metadata: Metadata = {
  title: 'Privacy Policy - Entrix AI',
  description: 'Privacy policy for CallKeep, the AI receptionist product by Entrix AI.',
};

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-black via-neutral-950 to-black">
      <Navbar />

      <Section className="pt-32 pb-12 text-center">
        <h1 className="text-5xl md:text-7xl font-bold mb-6 bg-gradient-to-r from-indigo-400 to-fuchsia-500 bg-clip-text text-transparent">
          Privacy Policy
        </h1>
        <p className="text-xl text-neutral-300 max-w-2xl mx-auto mb-10 leading-relaxed">
          CallKeep is an AI receptionist service operated by Entrix AI Innovations Private Limited. 
          When customers call a business using CallKeep, the system may collect basic information 
          such as the caller’s phone number, name (if provided), and the service request described 
          during the call. This privacy policy explains what information may be processed and how it 
          is used to deliver leads and call summaries to the businesses using CallKeep.
        </p>
      </Section>

      <Section className="py-8">
        <h2 className="text-3xl md:text-5xl font-bold mb-4 text-center bg-gradient-to-r from-indigo-400 to-fuchsia-500 bg-clip-text text-transparent">
          What Data We Collect
        </h2>
        <p className="text-neutral-300 text-lg max-w-3xl mx-auto text-center leading-relaxed mb-8">
          When a caller interacts with CallKeep, the system may collect limited information necessary 
          to handle the call and deliver the lead to the business. This can include the caller’s phone 
          number, name if they choose to provide it, the service request described during the call, 
          and a short call summary or transcript generated by the AI system.
        </p>
      </Section>

      <Section className="py-8">
        <h2 className="text-3xl md:text-5xl font-bold mb-4 text-center bg-gradient-to-r from-indigo-400 to-fuchsia-500 bg-clip-text text-transparent">
          How We Use Your Data
        </h2>
        <p className="text-neutral-300 text-lg max-w-3xl mx-auto text-center leading-relaxed mb-8">
          Information collected during calls is used solely to help service businesses respond to 
          customer requests. CallKeep processes this information to generate call summaries, capture 
          lead details, and deliver the information to the business via email, SMS, or integrations. 
          Entrix AI does not sell or use this information for advertising.
        </p>
      </Section>

      <Section className="py-8">
        <h2 className="text-3xl md:text-5xl font-bold mb-4 text-center bg-gradient-to-r from-indigo-400 to-fuchsia-500 bg-clip-text text-transparent">
          Security & Encryption
        </h2>
        <p className="text-neutral-300 text-lg max-w-3xl mx-auto text-center leading-relaxed mb-8">
          Entrix AI uses secure infrastructure and industry‑standard encryption to protect data 
          processed through CallKeep. Access to call data is limited to the business receiving the 
          lead and to necessary infrastructure providers used to operate the service.
        </p>
      </Section>

      <Section className="py-8">
        <h2 className="text-3xl md:text-5xl font-bold mb-4 text-center bg-gradient-to-r from-indigo-400 to-fuchsia-500 bg-clip-text text-transparent">
          Your Choices & Rights
        </h2>
        <p className="text-neutral-300 text-lg max-w-3xl mx-auto text-center leading-relaxed mb-8">
          If you have questions about how information is handled or would like to request deletion of 
          data related to a specific call, you can contact Entrix AI at hello@entrixai.com. We will 
          respond to reasonable requests regarding access or removal of data where applicable.
        </p>
      </Section>

      <Footer />
    </main>
  );
}
